### ISSUE TITLE
fix and feat: backend

### ISSUE THREAD

**Issue by 07prajwal2000** [07prajwal2000/Shorty#3]
This issue will be tracked until the stable release of this product.

**Comment by 07prajwal2000** [comment]
## TODO: Features will be Implementing in this Issue
- [ ] CSRF tokens
- [ ] Basic Auth (Login, Signup, Password Reset, Email verification)
- [x] Host React site in Golang
- [x] Fully functional URL shortener
- [x] Database Integration (Postgres 🤔)

**Comment by 07prajwal2000** [comment]
Completed 3/5 todos. 🙌
